version: '3.5'

networks:
  docker-containers-log-manager-net:
    driver: bridge

volumes:
    elasticsearch-data:
    filebeat-data:
    kibana-data:
    logstash-data:

services:

  elasticsearch:
    image: lekpamartin/elasticsearch-docker-containers-log-manager
    hostname: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    restart: unless-stopped
    networks:
      - docker-containers-log-manager-net
    labels:
      org.label-schema.group: "docker-containers-log-manager"
      co.elastic.logs/disable: true

  kibana:
    image: lekpamartin/kibana-docker-containers-log-manager
    hostname: kibana
    volumes:
      - kibana-data:/usr/share/kibana/data
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    restart: unless-stopped
    networks:
      - docker-containers-log-manager-net
    ports:
      #- "5601:5601"
      - "5601"
    labels:
      org.label-schema.group: "docker-containers-log-manager"
      co.elastic.logs/disable: true

  logstash:
    image: lekpamartin/logstash-docker-containers-log-manager
    hostname: logstash
    volumes:
      - logstash-data:/usr/share/logstash/data
    environment:
      - ELASTICSEARCH_URL=elasticsearch:9200
    restart: unless-stopped
    networks:
      - docker-containers-log-manager-net
    labels:
      org.label-schema.group: "docker-containers-log-manager"
      co.elastic.logs/disable: true

  filebeat:
    image: lekpamartin/filebeat-docker-containers-log-manager
    hostname: filebeat
    user: root
    volumes:
      - filebeat-data:/usr/share/filebeat/data
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - LOGSTASH_HOSTS="logstash:5044"
    restart: unless-stopped
    networks:
      - docker-containers-log-manager-net
    labels:
      org.label-schema.group: "docker-containers-log-manager"
      co.elastic.logs/disable: true
